name: Sync Branch Master to Develop

on:
  push:
    branches:
      - 'master'

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'develop'

    - name: Test Print
      run: |
        git log -1

    # - name: Merge
    #   run: git merge --no-ff -m "Merge branch 'master' into develop" master
